# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
